blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/DolphBit/mb-automation-ahk/discussions
    about: GitHub Discussions
  - name: Contact E-Mail
    url: hello@dolphbit.de
    about: Contact me directly
